// Auto-generated from frontend artifacts.js
export const ITEM_CATALOG = [
  {"id":"old_dumbbell","name":"Стара Гантеля","rarity":"common","icon":"/icons/old_dumbbell.png"},
  {"id":"protein_bar_fake","name":"Протеїновий Батончик","rarity":"common","icon":"/icons/protein_bar_fake.png"},
  {"id":"motivation_post","name":"Мотивуючий Пост","rarity":"common","icon":"/icons/motivation_post.png"},
  {"id":"gym_selfie","name":"Селфі з Тренажерки","rarity":"common","icon":"/icons/gym_selfie.png"},
  {"id":"skuf_belly","name":"Пузо Скуфа","rarity":"common","icon":"/icons/skuf_belly.png"},
  {"id":"dirty_underpants","name":"Обісрані Труси","rarity":"common","icon":"/icons/dirty_underpants.png"},
  {"id":"mamas_towel","name":"Рушник Мами","rarity":"common","icon":"/icons/mamas_towel.png"},
  {"id":"neighbour_bychok","name":"Бичок від Сусіда Петра","rarity":"common","icon":"/icons/neighbour_bychok.png"},
  {"id":"shaurma_bag","name":"Шаурма в Пакеті","rarity":"common","icon":"/icons/shaurma_bag.png"},
  {"id":"dead_phone","name":"Телефон на 1%","rarity":"common","icon":"/icons/dead_phone.png"},
  {"id":"borscht_bucket","name":"Відро Борщу","rarity":"common","icon":"/icons/borscht_bucket.png"},
  {"id":"cat_meme","name":"Мем з Котом","rarity":"common","icon":"/icons/cat_meme.png"},
  {"id":"kovbasa_sandwich","name":"Бутерброд з Ковбасою","rarity":"common","icon":"/icons/kovbasa_sandwich.png"},
  {"id":"ozon_dumbbell","name":"Гантеля з Ozonu","rarity":"common","icon":"/icons/ozon_dumbbell.png"},
  {"id":"straw_hat","name":"Солом'яний Капелюх","rarity":"common","icon":"/icons/straw_hat.png"},
  {"id":"expired_kefir","name":"Прострочений Кефір","rarity":"common","icon":"/icons/expired_kefir.png"},
  {"id":"lays_chips","name":"Чипси Лейз","rarity":"common","icon":"/icons/lays_chips.png"},
  {"id":"grandma_tights","name":"Колготки Бабусі","rarity":"common","icon":"/icons/grandma_tights.png"},
  {"id":"broken_scale","name":"Зламані Ваги","rarity":"common","icon":"/icons/broken_scale.png"},
  {"id":"diet_cola","name":"Дієтична Кола","rarity":"common","icon":"/icons/diet_cola.png"},
  {"id":"chest_wood","name":"Дерев'яний Ящик","rarity":"common","icon":"📫"},
  {"id":"chest_wood","name":"Дерев'яний Ящик","rarity":"common","icon":"📫"},
  {"id":"adidas_shoes","name":"Кросівки \"Адідас\"","rarity":"uncommon","icon":"/icons/adidas_shoes.png"},
  {"id":"cossack_thermos","name":"Термос Козака","rarity":"uncommon","icon":"/icons/cossack_thermos.png"},
  {"id":"premium_buckwheat","name":"Гречка Преміум","rarity":"uncommon","icon":"/icons/premium_buckwheat.png"},
  {"id":"yoga_mat","name":"Килимок для Йоги","rarity":"uncommon","icon":"/icons/yoga_mat.png"},
  {"id":"grandma_slipper","name":"Тапок Бабусі","rarity":"uncommon","icon":"/icons/grandma_slipper.png"},
  {"id":"salo_first_grade","name":"Сало Першого Сорту","rarity":"uncommon","icon":"/icons/salo_first_grade.png"},
  {"id":"water_bottle_2l","name":"Пляшка Води 2л","rarity":"uncommon","icon":"/icons/water_bottle_2l.png"},
  {"id":"sport_leggings","name":"Спортивні Лосини","rarity":"uncommon","icon":"/icons/sport_leggings.png"},
  {"id":"protein_shaker","name":"Протеїновий Шейкер","rarity":"uncommon","icon":"/icons/protein_shaker.png"},
  {"id":"jump_rope","name":"Скакалка","rarity":"uncommon","icon":"/icons/jump_rope.png"},
  {"id":"morning_alarm","name":"Ранковий Будильник","rarity":"uncommon","icon":"/icons/morning_alarm.png"},
  {"id":"office_slippers","name":"Офісні Капці","rarity":"uncommon","icon":"/icons/office_slippers.png"},
  {"id":"homemade_mead","name":"Медовуха Дідова","rarity":"uncommon","icon":"/icons/homemade_mead.png"},
  {"id":"scooter","name":"Самокат","rarity":"uncommon","icon":"/icons/scooter.png"},
  {"id":"vyshyvanka","name":"Вишиванка","rarity":"uncommon","icon":"/icons/vyshyvanka.png"},
  {"id":"fathers_belt","name":"Батьківський Ремінь","rarity":"uncommon","icon":"/icons/fathers_belt.png"},
  {"id":"salmon_piece","name":"Кусок Лосося","rarity":"uncommon","icon":"/icons/salmon_piece.png"},
  {"id":"garden_shovel","name":"Лопата Городника","rarity":"uncommon","icon":"/icons/garden_shovel.png"},
  {"id":"bike","name":"Старий Велосипед","rarity":"uncommon","icon":"/icons/bike.png"},
  {"id":"coffee_thermos","name":"Термос з Кавою","rarity":"uncommon","icon":"/icons/coffee_thermos.png"},
  {"id":"chest_iron","name":"Залізний Куфр","rarity":"uncommon","icon":"🗃️"},
  {"id":"chest_iron","name":"Залізний Куфр","rarity":"uncommon","icon":"🗃️"},
  {"id":"lviv_beer","name":"Пиво Львівське 1715","rarity":"rare","icon":"/icons/lviv_beer.png"},
  {"id":"magic_burger","name":"Бургер МакМагічний","rarity":"rare","icon":"/icons/magic_burger.png"},
  {"id":"lucky_scales","name":"Щасливі Ваги","rarity":"rare","icon":"/icons/lucky_scales.png"},
  {"id":"uncle_bob_advice","name":"Порада Дядька Бориса","rarity":"rare","icon":"/icons/uncle_bob_advice.png"},
  {"id":"gigachad_aura","name":"Аура Гігачада","rarity":"rare","icon":"/icons/gigachad_aura.png"},
  {"id":"shevchenko_icon","name":"Ікона Тараса","rarity":"rare","icon":"/icons/shevchenko_icon.png"},
  {"id":"sport_medal","name":"Медаль \"За Спорт\"","rarity":"rare","icon":"/icons/sport_medal.png"},
  {"id":"gym_ticket","name":"Квиток у Тренажерку","rarity":"rare","icon":"/icons/gym_ticket.png"},
  {"id":"zero_soda","name":"Газировка Zero","rarity":"rare","icon":"/icons/zero_soda.png"},
  {"id":"buckwheat_diet","name":"Гречана Дієта","rarity":"rare","icon":"/icons/buckwheat_diet.png"},
  {"id":"calorie_notebook","name":"Блокнот Калорій","rarity":"rare","icon":"/icons/calorie_notebook.png"},
  {"id":"sauna_pass","name":"Пропуск до Сауни","rarity":"rare","icon":"/icons/sauna_pass.png"},
  {"id":"finish_tape","name":"Стрічка Фінішу","rarity":"rare","icon":"/icons/finish_tape.png"},
  {"id":"healthy_recipe","name":"Книга Рецептів","rarity":"rare","icon":"/icons/healthy_recipe.png"},
  {"id":"body_tape","name":"Сантиметрова Стрічка","rarity":"rare","icon":"/icons/body_tape.png"},
  {"id":"olive_oil","name":"Оливкова Олія","rarity":"rare","icon":"/icons/olive_oil.png"},
  {"id":"motivation_kit","name":"Аптечка Мотивації","rarity":"rare","icon":"/icons/motivation_kit.png"},
  {"id":"protein_powder","name":"Протеїновий Порошок","rarity":"rare","icon":"/icons/protein_powder.png"},
  {"id":"running_watch","name":"Розумний Годинник","rarity":"rare","icon":"/icons/running_watch.png"},
  {"id":"hiking_boots","name":"Трекінгові Черевики","rarity":"rare","icon":"/icons/hiking_boots.png"},
  {"id":"chest_gold","name":"Козацька Скриня","rarity":"rare","icon":"🧰"},
  {"id":"chest_gold","name":"Козацька Скриня","rarity":"rare","icon":"🧰"},
  {"id":"cheat_ring","name":"Кільце Чіт-Коду","rarity":"epic","icon":"/icons/cheat_ring.png"},
  {"id":"schwarzenegger_ghost","name":"Привид Шварценеггера","rarity":"epic","icon":"/icons/schwarzenegger_ghost.png"},
  {"id":"weight_joystick","name":"Джойстик Ваги","rarity":"epic","icon":"/icons/weight_joystick.png"},
  {"id":"shaurma_vip","name":"Шаурма VIP","rarity":"epic","icon":"/icons/shaurma_vip.png"},
  {"id":"cossack_pipe","name":"Козацька Люлька","rarity":"epic","icon":"/icons/cossack_pipe.png"},
  {"id":"zaluzhnyi_cap","name":"Кепка Залужного","rarity":"epic","icon":"/icons/zaluzhnyi_cap.png"},
  {"id":"ufo_over_ukraine","name":"НЛО над Батьківщиною","rarity":"epic","icon":"/icons/ufo_over_ukraine.png"},
  {"id":"gold_headphones","name":"Золоті Навушники","rarity":"epic","icon":"/icons/gold_headphones.png"},
  {"id":"marathon_trophy","name":"Трофей Марафонця","rarity":"epic","icon":"/icons/marathon_trophy.png"},
  {"id":"magic_scales_2","name":"Магічні Ваги 2.0","rarity":"epic","icon":"/icons/magic_scales_2.png"},
  {"id":"dietologist_cert","name":"Сертифікат Дієтолога","rarity":"epic","icon":"/icons/dietologist_cert.png"},
  {"id":"balcony_bar","name":"Турнік з Балкону","rarity":"epic","icon":"/icons/balcony_bar.png"},
  {"id":"smaller_pants","name":"Штани на 2 Розміри Менше","rarity":"epic","icon":"/icons/smaller_pants.png"},
  {"id":"magic_wand","name":"Чарівна Паличка Дієти","rarity":"epic","icon":"/icons/magic_wand.png"},
  {"id":"willpower_cup","name":"Кубок Сили Волі","rarity":"epic","icon":"/icons/willpower_cup.png"},
  {"id":"thermonuclear_coffee","name":"Термоядерна Кава","rarity":"epic","icon":"/icons/thermonuclear_coffee.png"},
  {"id":"borsetka","name":"Борсетка Успіху","rarity":"epic","icon":"/icons/borsetka.png"},
  {"id":"dragon_kimono","name":"Кімоно Дракона","rarity":"epic","icon":"/icons/dragon_kimono.png"},
  {"id":"fish_tank","name":"Акваріум з Коропом","rarity":"epic","icon":"/icons/fish_tank.png"},
  {"id":"diet_drop_epic","name":"Вільний Прийом Їжі","rarity":"epic","icon":"/icons/diet_drop_epic.png"},
  {"id":"chest_epic","name":"Гетьманська Скарбниця","rarity":"epic","icon":"💼"},
  {"id":"chest_epic","name":"Гетьманська Скарбниця","rarity":"epic","icon":"💼"},
  {"id":"cossack_kettlebell","name":"Золота Гиря Козака","rarity":"legendary","icon":"/icons/cossack_kettlebell.png"},
  {"id":"anti_burger_sword","name":"Меч Анти-Бургер","rarity":"legendary","icon":"/icons/anti_burger_sword.png"},
  {"id":"pandora_box","name":"Скриня Пандори","rarity":"legendary","icon":"/icons/pandora_box.png"},
  {"id":"gigachad_aura_max","name":"Аура Гігачада MAX","rarity":"legendary","icon":"/icons/gigachad_aura_max.png"},
  {"id":"zsu_tractor","name":"Трактор ЗСУ","rarity":"legendary","icon":"/icons/zsu_tractor.png"},
  {"id":"zaporizhian_trousers","name":"Шаровари Запорожця","rarity":"legendary","icon":"/icons/zaporizhian_trousers.png"},
  {"id":"hetman_mace","name":"Булава Гетьмана","rarity":"legendary","icon":"/icons/hetman_mace.png"},
  {"id":"mazepas_hat","name":"Шапка Мазепи","rarity":"legendary","icon":"/icons/mazepas_hat.png"},
  {"id":"dnipro_water","name":"Свята Вода Дніпра","rarity":"legendary","icon":"/icons/dnipro_water.png"},
  {"id":"cossack_mustang","name":"Кінь Козацький","rarity":"legendary","icon":"/icons/cossack_mustang.png"},
  {"id":"fate_finger","name":"Перст Долі","rarity":"legendary","icon":"/icons/fate_finger.png"},
  {"id":"heavenly_trident","name":"Тризуб Небесний","rarity":"legendary","icon":"/icons/heavenly_trident.png"},
  {"id":"crown_of_slim","name":"Корона Схудлих","rarity":"legendary","icon":"/icons/crown_of_slim.png"},
  {"id":"cossack_cross","name":"Хрест Козацький","rarity":"legendary","icon":"/icons/cossack_cross.png"},
  {"id":"taras_sword","name":"Булат Тараса","rarity":"legendary","icon":"/icons/taras_sword.png"},
  {"id":"iron_helmet","name":"Козацький Шолом","rarity":"legendary","icon":"/icons/iron_helmet.png"},
  {"id":"hetman_scepter","name":"Скіпетр Гетьмана","rarity":"legendary","icon":"/icons/hetman_scepter.png"},
  {"id":"cossack_bandura","name":"Бандура Козацька","rarity":"legendary","icon":"/icons/cossack_bandura.png"},
  {"id":"magic_borsch","name":"Магічний Борщ","rarity":"legendary","icon":"/icons/magic_borsch.png"},
  {"id":"cossack_eagle","name":"Козацький Орел","rarity":"legendary","icon":"/icons/cossack_eagle.png"},
  {"id":"chest_legendary","name":"Скриня Мамая","rarity":"legendary","icon":"🎁"},
  {"id":"chest_legendary","name":"Скриня Мамая","rarity":"legendary","icon":"🎁"},
];

export const RARITY_LABELS = {
  common: "Звичайний",
  uncommon: "Незвичайний",
  rare: "Рідкісний",
  epic: "Епічний",
  legendary: "Легендарний",
};
